#!/usr/bin/env node
'use strict'

/**
 * Build standalone HTML wiki under docs/wiki-site/.
 * Output: manifest.json + assets/wiki-bundle.js (all page HTML embedded).
 *
 * Run: npm run wiki:build
 * Open: docs/wiki-site/index.html in any browser (file:// or static host).
 */

const fs = require('fs')
const path = require('path')
const { markdownToHtml } = require('./md-to-html')
const { resolveWikiLink } = require('./resolve-link')

const REPO_ROOT = path.join(__dirname, '..', '..')
const DOCS_ROOT = path.join(REPO_ROOT, 'docs')
/* HIGHASCG_WIKI_OUT_DIR lets a caller build somewhere other than the committed site — the smoke
 * test uses it so a gate run does not rewrite docs/wiki-site (its generatedAt stamp dirtied the
 * working tree on every `npm run test:ci`). Unset = normal build into docs/wiki-site/. */
const SITE_DIR = process.env.HIGHASCG_WIKI_OUT_DIR
	? path.resolve(process.env.HIGHASCG_WIKI_OUT_DIR)
	: path.join(DOCS_ROOT, 'wiki-site')
const MANIFEST_PATH = path.join(SITE_DIR, 'manifest.json')
const BUNDLE_PATH = path.join(SITE_DIR, 'assets', 'wiki-bundle.js')

const PATH_RULES = require('./wiki-pages.config')

const SKIP_DIRS = new Set(['internal', 'wiki-site'])
const SKIP_FILES = new Set(['wiki/api/openapi.yaml'])

function walkMd(dir, base = '') {
	const out = []
	if (!fs.existsSync(dir)) return out
	for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
		if (ent.name.startsWith('.')) continue
		const rel = base ? `${base}/${ent.name}` : ent.name
		if (ent.isDirectory()) {
			if (SKIP_DIRS.has(ent.name)) continue
			out.push(...walkMd(path.join(dir, ent.name), rel))
			continue
		}
		if (!ent.name.endsWith('.md')) continue
		if (SKIP_FILES.has(rel)) continue
		out.push(rel.replace(/\\/g, '/'))
	}
	return out
}

function ruleFor(rel) {
	for (const rule of PATH_RULES) {
		if (rule.match.test(rel)) return rule
	}
	return { category: 'Reference', order: 900 }
}

function titleFromFile(rel, override) {
	if (override) return override
	const base = path.basename(rel, '.md')
	return base.replace(/[-_]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}

function firstParagraph(md) {
	const lines = md.split('\n')
	let inFence = false
	for (const line of lines) {
		if (line.startsWith('```')) {
			inFence = !inFence
			continue
		}
		if (inFence) continue
		if (line.startsWith('#')) continue
		const t = line.trim()
		if (t) return t.slice(0, 160)
	}
	return ''
}

function slugFromRel(rel) {
	return rel.replace(/\.md$/i, '').replace(/\//g, '--')
}

function main() {
	const files = walkMd(DOCS_ROOT)
	const pages = []

	for (const rel of files.sort()) {
		const rule = ruleFor(rel)
		const abs = path.join(DOCS_ROOT, rel)
		let md
		try {
			md = fs.readFileSync(abs, 'utf8')
		} catch {
			continue
		}
		const h1 = md.match(/^#\s+(.+)$/m)
		pages.push({
			id: slugFromRel(rel),
			title: h1 ? h1[1].trim() : titleFromFile(rel, rule.title),
			file: rel,
			category: rule.category,
			group: rule.group || undefined,
			description: firstParagraph(md),
			order: rule.order,
		})
	}

	pages.sort((a, b) => {
		if (a.category !== b.category) {
			const catOrder = ['Home', 'Getting started', 'Installation', 'Storage & USB', 'API reference', 'Integration', 'Audio', 'Reference']
			return (catOrder.indexOf(a.category) - catOrder.indexOf(b.category)) || a.category.localeCompare(b.category)
		}
		if (a.order !== b.order) return a.order - b.order
		return a.title.localeCompare(b.title)
	})

	const pageByFile = new Map(pages.map((p) => [p.file, p]))
	const content = {}

	for (const page of pages) {
		const md = fs.readFileSync(path.join(DOCS_ROOT, page.file), 'utf8')
		const html = markdownToHtml(md, {
			linkResolver: (href) =>
				resolveWikiLink(href, page.file, pageByFile, page.id, DOCS_ROOT, SITE_DIR, REPO_ROOT),
		})
		content[page.id] = html
	}

	const categories = [...new Set(pages.map((p) => p.category))]
	const manifest = {
		version: 2,
		standalone: true,
		generatedAt: new Date().toISOString(),
		defaultPage: pages.find((p) => p.file === 'wiki/README.md')?.id || pages[0]?.id || 'wiki--README',
		categories,
		pages,
	}

	fs.mkdirSync(path.dirname(BUNDLE_PATH), { recursive: true })
	fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n')
	fs.writeFileSync(
		BUNDLE_PATH,
		'/* Generated by tools/wiki/build-wiki.js — do not edit */\n' +
			'window.WIKI_BUNDLE=' +
			JSON.stringify({ manifest, content }) +
			';\n',
	)
	console.log(`Built ${pages.length} pages → ${MANIFEST_PATH}`)
	console.log(`Embedded HTML → ${BUNDLE_PATH}`)
}

main()
