'use strict'

/** Shared page categorization rules for wiki build. */
module.exports = [
	{ match: /^README\.md$/, category: 'Home', order: 0, title: 'Documentation home' },
	{ match: /^wiki\/README\.md$/, category: 'Home', order: 1, title: 'Wiki index' },
	{ match: /^ARCHITECTURE\.md$/, category: 'Getting started', order: 10 },
	{ match: /^PLAN_SERVER_CLIENT_SPLIT\.md$/, category: 'Getting started', order: 11 },
	{ match: /^MODULES\.md$/, category: 'Getting started', order: 12 },
	{ match: /^MANUAL_INSTALL\.md$/, category: 'Installation', order: 20 },
	{ match: /^LIVE_USB_IMAGE\.md$/, category: 'Installation', order: 21 },
	{ match: /^CALAMARES_INSTALL_TO_DISK\.md$/, category: 'Installation', order: 21.5 },
	{ match: /^wiki\/install\/calamares-install-to-disk\.md$/, category: 'Installation', order: 21.6, title: 'Calamares install (wiki)' },
	{ match: /^ISO_CONTENTS\.md$/, category: 'Installation', order: 22 },
	{ match: /^DEV_RELEASE_GITHUB\.md$/, category: 'Installation', order: 23 },
	{ match: /^BOOT_EMERGENCY_RECOVERY\.md$/, category: 'Installation', order: 24 },
	{ match: /^openbox_autostart\.md$/, category: 'Installation', order: 25 },
	{ match: /^BRIDGE_DISK_AND_USB_EXFAT\.md$/, category: 'Storage & USB', order: 30 },
	{ match: /^WO47_ISO_VS_EXFAT\.md$/, category: 'Storage & USB', order: 31 },
	{ match: /^EXFAT_SERVER_UPDATE\.md$/, category: 'Storage & USB', order: 32 },
	{ match: /^USB_AUTO_MOUNT_UBUNTU\.md$/, category: 'Storage & USB', order: 33 },
	{ match: /^casparcg-linux-usb-guide\.md$/, category: 'Storage & USB', order: 34 },
	{ match: /^CASPAR_IMAGE_VS_HIGHASCG_OVERLAY\.md$/, category: 'Storage & USB', order: 35 },
	{ match: /^HIGHASCG_PASSWORDLESS_SUDO\.md$/, category: 'Installation', order: 26 },
	{ match: /^wiki\/api\/README\.md$/, category: 'API reference', order: 40, group: 'Overview' },
	{ match: /^wiki\/api\/scene-take\.md$/, category: 'API reference', order: 41, group: 'Scene & playback' },
	{ match: /^wiki\/api\/playback\.md$/, category: 'API reference', order: 42, group: 'Scene & playback' },
	{ match: /^wiki\/api\/playback-and-amcp\.md$/, category: 'API reference', order: 43, group: 'Scene & playback' },
	{ match: /^wiki\/api\/mixer\.md$/, category: 'API reference', order: 44, group: 'Mixer & CG' },
	{ match: /^wiki\/api\/mixer-cg-scene\.md$/, category: 'API reference', order: 45, group: 'Mixer & CG' },
	{ match: /^wiki\/api\/cg\.md$/, category: 'API reference', order: 46, group: 'Mixer & CG' },
	{ match: /^wiki\/api\/project\.md$/, category: 'API reference', order: 47, group: 'Project & state' },
	{ match: /^wiki\/api\/project-state-media\.md$/, category: 'API reference', order: 48, group: 'Project & state' },
	{ match: /^wiki\/api\/state-and-media\.md$/, category: 'API reference', order: 49, group: 'Project & state' },
	{ match: /^wiki\/api\/timelines\.md$/, category: 'API reference', order: 50, group: 'Timelines & streaming' },
	{ match: /^wiki\/api\/timelines-multiview\.md$/, category: 'API reference', order: 51, group: 'Timelines & streaming' },
	{ match: /^wiki\/api\/streaming-audio-osc\.md$/, category: 'API reference', order: 52, group: 'Timelines & streaming' },
	{ match: /^wiki\/api\/system-settings-hardware\.md$/, category: 'API reference', order: 53, group: 'System & hardware' },
	{ match: /^wiki\/api\/network-tailscale\.md$/, category: 'API reference', order: 53.5, group: 'System & hardware' },
	{ match: /^wiki\/api\/ingest-usb-plugins\.md$/, category: 'API reference', order: 54, group: 'System & hardware' },
	{ match: /^api-reference\.md$/, category: 'API reference', order: 55, group: 'Overview', title: 'Legacy API overview' },
	{ match: /^osc-integration\.md$/, category: 'Integration', order: 60 },
	{ match: /^companion-websocket-catalog-bootstrap\.md$/, category: 'Integration', order: 61 },
	{ match: /^companion-module-ui-selection\.md$/, category: 'Integration', order: 62 },
	{ match: /^caspar_config_explained\.md$/, category: 'Integration', order: 63 },
	{ match: /^guides\/audio\//, category: 'Audio', order: 70 },
	{ match: /^reference\/audio\//, category: 'Audio', order: 71 },
	{ match: /^reference\//, category: 'Reference', order: 80 },
	{ match: /^decoupled_architecture_list\.md$/, category: 'Reference', order: 81 },
]
