'use strict'

const { casparServerDefaults } = require('./defaults-caspar-server')
const { editorDefaultsDefaults } = require('./editor-defaults')
const { replicationDefaults } = require('./defaults-replication')

/** Top-level defaults excluding casparServer (merged in defaults.js). */
function coreDefaults() {
	return {
		caspar: {
			host: '127.0.0.1',
			port: 5250,
		},
		amcp_batch: false,
		amcp_max_batch_commands: 64,
		amcp_mixer_commit_before_amcp_batch: true,
		offline_mode: false,
		screen_1_force_os_resolution: false,
		screen_2_force_os_resolution: false,
		screen_3_force_os_resolution: false,
		screen_4_force_os_resolution: false,
		host_stats: {
			scan_folder: false,
		},
		osc_info_supplement_ms: null,
		hq_thumbnail_prewarm_on_start: true,
		hq_thumbnail_prewarm_on_media_refresh: true,
		casparServer: casparServerDefaults(),
		usbIngest: {
			enabled: true,
			defaultSubfolder: '',
			overwritePolicy: 'rename',
			verifyHash: false,
		},
		projectScopedMedia: {
			enabled: true,
			location: 'internal',
		},
		local_template_path: '',
		server: {
			httpPort: 4200,
			wsPort: 4200,
			bindAddress: '0.0.0.0',
		},
		osc: {
			enabled: true,
			listenPort: 6251,
			listenAddress: '0.0.0.0',
			peakHoldMs: 2000,
			emitIntervalMs: 50,
			staleTimeoutMs: 5000,
		},
		ui: {
			oscFooterVu: true,
			rundownPlaybackTimer: true,
			nuclearRequirePassword: false,
			nuclearPassword: '',
		},
		composePreview: {
			mode: 'canvas',
			tickHz: 8,
			tickIntervalMs: 40,
			fps: 2,
			resolutionScale: 'half',
			jpegQuality: 10,
			basenamePrefix: 'highascg_preview',
			maxWidth: 480,
			channels: 'compose_visible',
			embedConsumersInCasparConfig: true,
			attachViaAmcp: true,
			pauseConsumerWhenIdle: false,
			companionThumbEnabled: false,
			companionThumbSize: 144,
			companionThumbIntervalMs: 1000,
		},
		editorDefaults: editorDefaultsDefaults(),
		audioRouting: {
			programLayout: 'stereo',
			programOutput: 'default',
			programAlsaDevice: '',
			programFfmpegPath: '',
			programFfmpegArgs: '',
			monitorOutput: 'default',
			monitorAlsaDevice: '',
			monitorFfmpegPath: '',
			monitorFfmpegArgs: '',
			browserMonitor: 'pgm',
			programSystemAudioDevices: ['', '', '', ''],
			previewSystemAudioEnabled: [false, false, false, false],
			previewSystemAudioDevices: ['', '', '', ''],
			audioPreview: {
				enabled: false,
				bus: 'preview_1',
				screenIndex: 1,
				deviceName: '',
				soloLayerStart: 1,
				soloLayerCount: 8,
				defaultSource: 'preview_1',
			},
		},
		x11_horizontal_swap: false,
		multiview_system_id: '',
		multiview_os_mode: '',
		multiview_os_rate: '',
		dmx: {
			enabled: false,
			debugLogDmx: false,
			fps: 25,
			fixtures: [],
			artnetInputEnabled: true,
			artnetInputPort: 6454,
			artnetInputScreenIndex: 0,
			artnetInputLogIntervalMs: 60_000,
			artnetInputWsIntervalMs: 500,
			artnetInputStatsIntervalMs: 10_000,
		},
		rtmp: {
			enabled: false,
			programOutputsEnabled: true,
			previewOutputsEnabled: false,
			multiviewOutputEnabled: true,
			destinations: [
				{
					enabled: false,
					label: 'Encoder 1',
					rtmpServerUrl: '',
					streamKey: '',
					rtmpUrl: '',
					inputTarget: 'program_1',
					videoCodec: 'h264',
					videoBitrateKbps: 4500,
					encoderPreset: 'veryfast',
					audioSource: 'muxed',
					audioBitrateKbps: 128,
				},
				{
					enabled: false,
					label: 'Encoder 2',
					rtmpServerUrl: '',
					streamKey: '',
					rtmpUrl: '',
					inputTarget: 'program_1',
					videoCodec: 'h264',
					videoBitrateKbps: 4500,
					encoderPreset: 'veryfast',
					audioSource: 'muxed',
					audioBitrateKbps: 128,
				},
				{
					enabled: false,
					label: 'Encoder 3',
					rtmpServerUrl: '',
					streamKey: '',
					rtmpUrl: '',
					inputTarget: 'multiview',
					videoCodec: 'h264',
					videoBitrateKbps: 4500,
					encoderPreset: 'veryfast',
					audioSource: 'muxed',
					audioBitrateKbps: 128,
				},
				{
					enabled: false,
					label: 'Encoder 4',
					rtmpServerUrl: '',
					streamKey: '',
					rtmpUrl: '',
					inputTarget: 'program_1',
					videoCodec: 'h264',
					videoBitrateKbps: 4500,
					encoderPreset: 'veryfast',
					audioSource: 'muxed',
					audioBitrateKbps: 128,
				},
			],
		},
		streamingChannel: {
			enabled: false,
			videoMode: '1080p5000',
			videoSource: 'program_1',
			audioSource: 'follow_video',
			casparChannel: null,
			dedicatedOutputChannel: false,
			rtmpServerUrl: '',
			streamKey: '',
			rtmpQuality: 'medium',
			contentLayer: 10,
			decklinkDevice: 0,
		},
		plugins: {
			entries: {},
		},
		cgStudio: {
			httpPort: 4300,
			bindAddress: '127.0.0.1',
		},
		recordOutputs: [
			{
				id: 'rec_1',
				label: 'Rec1',
				enabled: true,
				name: 'Rec1',
				source: 'program_1',
				crf: 26,
				videoCodec: 'h264',
				videoBitrateKbps: 4500,
				encoderPreset: 'veryfast',
				audioCodec: 'aac',
				audioBitrateKbps: 128,
			},
		],
		screenDestinations: {
			version: 1,
			edidNotes: '',
		},
		gpuPhysicalTopology: [
			{ physicalPortId: 'gpu_p0', slotOrder: 0, dpA: 'DP-0', dpB: 'DP-1', connectorNumber: 0, location: 0 },
			{ physicalPortId: 'gpu_p1', slotOrder: 1, dpA: 'HDMI-0', dpB: 'HDMI-1', connectorNumber: 1, location: 1 },
			{ physicalPortId: 'gpu_p2', slotOrder: 2, dpA: 'DP-2', dpB: 'DP-3', connectorNumber: 2, location: 2 },
			{ physicalPortId: 'gpu_p3', slotOrder: 3, dpA: 'DP-4', dpB: 'DP-5', connectorNumber: 3, location: 3 },
		],
		deviceGraph: {
			version: 1,
			devices: [{ id: 'caspar_host', role: 'caspar_host', label: 'Caspar / HighAsCG host' }],
			connectors: [],
			edges: [],
			layout: {},
		},
		replication: replicationDefaults(),
		machineProfile: {
			defaultProjectFps: 50,
		},
		network: {
			primaryInterface: '',
			mode: 'dhcp',
			static: {
				address: '',
				prefixLength: 24,
				gateway: '',
				dns: [],
			},
		},
	}
}

module.exports = { coreDefaults }
